CREATE TABLE tt_content
(
    tx_pagedoctor_text_1 text,
    tx_pagedoctor_text_2 text,
    tx_pagedoctor_text_3 text,
    tx_pagedoctor_text_4 text,
    tx_pagedoctor_text_5 text,
    tx_pagedoctor_text_6 text,
    tx_pagedoctor_text_7 text,
    tx_pagedoctor_text_8 text,
    tx_pagedoctor_text_9 text,
    tx_pagedoctor_text_10 text,
    tx_pagedoctor_text_11 text,
    tx_pagedoctor_text_12 text,
    tx_pagedoctor_text_13 text,
    tx_pagedoctor_text_14 text,
    tx_pagedoctor_text_15 text,
    tx_pagedoctor_text_16 text,
    tx_pagedoctor_text_17 text,
    tx_pagedoctor_text_18 text,
    tx_pagedoctor_text_19 text,
    tx_pagedoctor_text_20 text,
    tx_pagedoctor_text_21 text,
    tx_pagedoctor_text_22 text,
    tx_pagedoctor_text_23 text,
    tx_pagedoctor_text_24 text,
    tx_pagedoctor_text_25 text,
    tx_pagedoctor_text_26 text,
    tx_pagedoctor_text_27 text,
    tx_pagedoctor_text_28 text,
    tx_pagedoctor_text_29 text,
    tx_pagedoctor_text_30 text,
    tx_pagedoctor_text_31 text,
    tx_pagedoctor_text_32 text,
    tx_pagedoctor_text_33 text,
    tx_pagedoctor_text_34 text,
    tx_pagedoctor_text_35 text,
    tx_pagedoctor_text_36 text,
    tx_pagedoctor_text_37 text,
    tx_pagedoctor_text_38 text,
    tx_pagedoctor_text_39 text,
    tx_pagedoctor_text_40 text,
    tx_pagedoctor_text_41 text,
    tx_pagedoctor_text_42 text,
    tx_pagedoctor_text_43 text,
    tx_pagedoctor_text_44 text,
    tx_pagedoctor_text_45 text,
    tx_pagedoctor_text_46 text,
    tx_pagedoctor_text_47 text,
    tx_pagedoctor_text_48 text,
    tx_pagedoctor_text_49 text,
    tx_pagedoctor_text_50 text,
    tx_pagedoctor_integer_1 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_2 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_3 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_4 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_5 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_6 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_7 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_8 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_9 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_10 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_11 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_12 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_13 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_14 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_15 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_16 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_17 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_18 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_19 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_20 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_21 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_22 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_23 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_24 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_25 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_26 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_27 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_28 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_29 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_30 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_31 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_32 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_33 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_34 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_35 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_36 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_37 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_38 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_39 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_40 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_41 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_42 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_43 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_44 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_45 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_46 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_47 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_48 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_49 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_integer_50 int(11) DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_1 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_2 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_3 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_4 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_5 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_6 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_7 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_8 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_9 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_10 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_11 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_12 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_13 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_14 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_15 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_16 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_17 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_18 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_19 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_20 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_21 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_22 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_23 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_24 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_25 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_26 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_27 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_28 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_29 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_30 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_31 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_32 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_33 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_34 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_35 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_36 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_37 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_38 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_39 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_40 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_41 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_42 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_43 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_44 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_45 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_46 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_47 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_48 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_49 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_50 int(11) unsigned DEFAULT '0' NOT NULL
);