CREATE TABLE tt_content
(
    tx_pagedoctor_text_1 text,
    tx_pagedoctor_text_2 text,
    tx_pagedoctor_text_3 text,
    tx_pagedoctor_text_4 text,
    tx_pagedoctor_text_5 text,
    tx_pagedoctor_text_6 text,
    tx_pagedoctor_text_7 text,
    tx_pagedoctor_text_8 text,
    tx_pagedoctor_text_9 text,
    tx_pagedoctor_text_10 text,
    tx_pagedoctor_text_11 text,
    tx_pagedoctor_text_12 text,
    tx_pagedoctor_text_13 text,
    tx_pagedoctor_text_14 text,
    tx_pagedoctor_text_15 text,
    tx_pagedoctor_text_16 text,
    tx_pagedoctor_text_17 text,
    tx_pagedoctor_text_18 text,
    tx_pagedoctor_text_19 text,
    tx_pagedoctor_text_20 text,
    tx_pagedoctor_text_21 text,
    tx_pagedoctor_text_22 text,
    tx_pagedoctor_text_23 text,
    tx_pagedoctor_text_24 text,
    tx_pagedoctor_text_25 text,
    tx_pagedoctor_text_26 text,
    tx_pagedoctor_text_27 text,
    tx_pagedoctor_text_28 text,
    tx_pagedoctor_text_29 text,
    tx_pagedoctor_text_30 text,
    tx_pagedoctor_text_31 text,
    tx_pagedoctor_text_32 text,
    tx_pagedoctor_text_33 text,
    tx_pagedoctor_text_34 text,
    tx_pagedoctor_text_35 text,
    tx_pagedoctor_text_36 text,
    tx_pagedoctor_text_37 text,
    tx_pagedoctor_text_38 text,
    tx_pagedoctor_text_39 text,
    tx_pagedoctor_text_40 text,
    tx_pagedoctor_text_41 text,
    tx_pagedoctor_text_42 text,
    tx_pagedoctor_text_43 text,
    tx_pagedoctor_text_44 text,
    tx_pagedoctor_text_45 text,
    tx_pagedoctor_text_46 text,
    tx_pagedoctor_text_47 text,
    tx_pagedoctor_text_48 text,
    tx_pagedoctor_text_49 text,
    tx_pagedoctor_text_50 text,
    tx_pagedoctor_asset_1 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_2 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_3 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_4 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_5 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_6 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_7 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_8 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_9 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_10 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_11 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_12 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_13 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_14 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_15 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_16 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_17 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_18 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_19 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_20 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_21 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_22 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_23 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_24 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_25 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_26 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_27 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_28 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_29 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_30 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_31 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_32 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_33 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_34 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_35 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_36 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_37 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_38 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_39 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_40 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_41 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_42 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_43 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_44 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_45 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_46 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_47 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_48 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_49 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_asset_50 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_1 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_2 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_3 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_4 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_5 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_6 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_7 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_8 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_9 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_10 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_11 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_12 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_13 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_14 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_15 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_16 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_17 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_18 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_19 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_20 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_21 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_22 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_23 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_24 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_25 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_26 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_27 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_28 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_29 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_30 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_31 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_32 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_33 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_34 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_35 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_36 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_37 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_38 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_39 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_40 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_41 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_42 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_43 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_44 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_45 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_46 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_47 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_48 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_49 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_50 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_1 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_2 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_3 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_4 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_5 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_6 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_7 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_8 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_9 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_10 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_11 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_12 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_13 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_14 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_15 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_16 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_17 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_18 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_19 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_20 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_21 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_22 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_23 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_24 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_25 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_26 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_27 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_28 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_29 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_30 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_31 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_32 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_33 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_34 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_35 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_36 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_37 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_38 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_39 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_40 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_41 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_42 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_43 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_44 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_45 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_46 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_47 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_48 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_49 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_embed_parent_50 int(11) unsigned DEFAULT '0' NOT NULL,
    tx_pagedoctor_reference_1 text,
    tx_pagedoctor_reference_2 text,
    tx_pagedoctor_reference_3 text,
    tx_pagedoctor_reference_4 text,
    tx_pagedoctor_reference_5 text,
    tx_pagedoctor_reference_6 text,
    tx_pagedoctor_reference_7 text,
    tx_pagedoctor_reference_8 text,
    tx_pagedoctor_reference_9 text,
    tx_pagedoctor_reference_10 text,
    tx_pagedoctor_reference_11 text,
    tx_pagedoctor_reference_12 text,
    tx_pagedoctor_reference_13 text,
    tx_pagedoctor_reference_14 text,
    tx_pagedoctor_reference_15 text,
    tx_pagedoctor_reference_16 text,
    tx_pagedoctor_reference_17 text,
    tx_pagedoctor_reference_18 text,
    tx_pagedoctor_reference_19 text,
    tx_pagedoctor_reference_20 text,
    tx_pagedoctor_reference_21 text,
    tx_pagedoctor_reference_22 text,
    tx_pagedoctor_reference_23 text,
    tx_pagedoctor_reference_24 text,
    tx_pagedoctor_reference_25 text,
    tx_pagedoctor_reference_26 text,
    tx_pagedoctor_reference_27 text,
    tx_pagedoctor_reference_28 text,
    tx_pagedoctor_reference_29 text,
    tx_pagedoctor_reference_30 text,
    tx_pagedoctor_reference_31 text,
    tx_pagedoctor_reference_32 text,
    tx_pagedoctor_reference_33 text,
    tx_pagedoctor_reference_34 text,
    tx_pagedoctor_reference_35 text,
    tx_pagedoctor_reference_36 text,
    tx_pagedoctor_reference_37 text,
    tx_pagedoctor_reference_38 text,
    tx_pagedoctor_reference_39 text,
    tx_pagedoctor_reference_40 text,
    tx_pagedoctor_reference_41 text,
    tx_pagedoctor_reference_42 text,
    tx_pagedoctor_reference_43 text,
    tx_pagedoctor_reference_44 text,
    tx_pagedoctor_reference_45 text,
    tx_pagedoctor_reference_46 text,
    tx_pagedoctor_reference_47 text,
    tx_pagedoctor_reference_48 text,
    tx_pagedoctor_reference_49 text,
    tx_pagedoctor_reference_50 text,
    tx_pagedoctor_tablename varchar(64) DEFAULT '' NOT NULL,
    tx_pagedoctor_fieldname varchar(255) DEFAULT '' NOT NULL,
    KEY index_embed_1 (tx_pagedoctor_embed_parent_1),
    KEY index_embed_2 (tx_pagedoctor_embed_parent_2),
    KEY index_embed_3 (tx_pagedoctor_embed_parent_3),
    KEY index_embed_4 (tx_pagedoctor_embed_parent_4),
    KEY index_embed_5 (tx_pagedoctor_embed_parent_5),
    KEY index_embed_6 (tx_pagedoctor_embed_parent_6),
    KEY index_embed_7 (tx_pagedoctor_embed_parent_7),
    KEY index_embed_8 (tx_pagedoctor_embed_parent_8),
    KEY index_embed_9 (tx_pagedoctor_embed_parent_9),
    KEY index_embed_10 (tx_pagedoctor_embed_parent_10),
    KEY index_embed_11 (tx_pagedoctor_embed_parent_11),
    KEY index_embed_12 (tx_pagedoctor_embed_parent_12),
    KEY index_embed_13 (tx_pagedoctor_embed_parent_13),
    KEY index_embed_14 (tx_pagedoctor_embed_parent_14),
    KEY index_embed_15 (tx_pagedoctor_embed_parent_15),
    KEY index_embed_16 (tx_pagedoctor_embed_parent_16),
    KEY index_embed_17 (tx_pagedoctor_embed_parent_17),
    KEY index_embed_18 (tx_pagedoctor_embed_parent_18),
    KEY index_embed_19 (tx_pagedoctor_embed_parent_19),
    KEY index_embed_20 (tx_pagedoctor_embed_parent_20),
    KEY index_embed_21 (tx_pagedoctor_embed_parent_21),
    KEY index_embed_22 (tx_pagedoctor_embed_parent_22),
    KEY index_embed_23 (tx_pagedoctor_embed_parent_23),
    KEY index_embed_24 (tx_pagedoctor_embed_parent_24),
    KEY index_embed_25 (tx_pagedoctor_embed_parent_25),
    KEY index_embed_26 (tx_pagedoctor_embed_parent_26),
    KEY index_embed_27 (tx_pagedoctor_embed_parent_27),
    KEY index_embed_28 (tx_pagedoctor_embed_parent_28),
    KEY index_embed_29 (tx_pagedoctor_embed_parent_29),
    KEY index_embed_30 (tx_pagedoctor_embed_parent_30),
    KEY index_embed_31 (tx_pagedoctor_embed_parent_31),
    KEY index_embed_32 (tx_pagedoctor_embed_parent_32),
    KEY index_embed_33 (tx_pagedoctor_embed_parent_33),
    KEY index_embed_34 (tx_pagedoctor_embed_parent_34),
    KEY index_embed_35 (tx_pagedoctor_embed_parent_35),
    KEY index_embed_36 (tx_pagedoctor_embed_parent_36),
    KEY index_embed_37 (tx_pagedoctor_embed_parent_37),
    KEY index_embed_38 (tx_pagedoctor_embed_parent_38),
    KEY index_embed_39 (tx_pagedoctor_embed_parent_39),
    KEY index_embed_40 (tx_pagedoctor_embed_parent_40),
    KEY index_embed_41 (tx_pagedoctor_embed_parent_41),
    KEY index_embed_42 (tx_pagedoctor_embed_parent_42),
    KEY index_embed_43 (tx_pagedoctor_embed_parent_43),
    KEY index_embed_44 (tx_pagedoctor_embed_parent_44),
    KEY index_embed_45 (tx_pagedoctor_embed_parent_45),
    KEY index_embed_46 (tx_pagedoctor_embed_parent_46),
    KEY index_embed_47 (tx_pagedoctor_embed_parent_47),
    KEY index_embed_48 (tx_pagedoctor_embed_parent_48),
    KEY index_embed_49 (tx_pagedoctor_embed_parent_49),
    KEY index_embed_50 (tx_pagedoctor_embed_parent_50),
);

CREATE TABLE sys_file_reference
(
    type varchar(255) DEFAULT '0' NOT NULL,
);